#ifndef APPLICATIONLIBDECL_H
#define APPLICATIONLIBDECL_H

#include <QtCore/qglobal.h>

#if defined(APPLICATIONLIB_LIBRARY)
#  define APPLICATIONLIB_EXPORT Q_DECL_EXPORT
#else
#  define APPLICATIONLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // APPLICATIONLIBDECL_H

